ppr_project/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from api.views import EquipmentTypeViewSet, FacilityViewSet, ScheduleViewSet

app_name = 'api'

router = DefaultRouter()
router.register('schedules', ScheduleViewSet, basename='schedules')
router.register('facilities', FacilityViewSet, basename='facilities')
router.register('equipment_types', EquipmentTypeViewSet, basename='equipment_types')


urlpatterns = [
    path('', include(router.urls)),
]

ppr_project/ppr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('bugs/', include('bugtracker.urls', namespace='bugtracker')),
    path('ppradmin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ppr_project/reports/urls.py
from django.urls import path

from reports.views import (ConfirmScheduleCannotBeComplete,
                           ConfirmScheduleCompletedView,
                           ConfirmScheduleDateChangedView,
                           DateRangeScheduleView, DistributeNextMonthSchedules,
                           IndexView, NoPhotoScheduleView, OverDueScheduleView,
                           PhotoApprovalsDownloadView, ScheduleCalendarView,
                           ScheduleCreateView, ScheduleDetailInfoView,
                           SearchView, SelectDateRangeForScheduleView,
                           UncompletableScheduleView,
                           XlsxNextMonthDownloadView, XlsxReportDownloadView)

app_name = 'reports'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('overdue/<int:category_id>/', OverDueScheduleView.as_view(), name='overdue'),
    path('overdue/', OverDueScheduleView.as_view(), name='overdue'),
    path('uncompletable/', UncompletableScheduleView.as_view(), name='uncompletable'),
    path('no_photo_apporval/', NoPhotoScheduleView.as_view(), name='no_photo_apporval'),
    path('search/', SearchView.as_view(), name='search'),
    path('select_date_range/', SelectDateRangeForScheduleView.as_view(), name='select_date_range'),
    path('schedule/<int:pk>/', ScheduleDetailInfoView.as_view(), name='schedule_detail'),
    path('schedule/confirm_completed/', ConfirmScheduleCompletedView.as_view(), name='confirm_schedule_completed'),
    path('schedule/confirm_date_changed/', ConfirmScheduleDateChangedView.as_view(), name='confirm_date_changed'),
    path(
        'schedule/confirm_cant_complete/',
        ConfirmScheduleCannotBeComplete.as_view(),
        name='confirm_schedule_cant_complete'
    ),
    path('xlsx_report/', XlsxReportDownloadView.as_view(), name='xlsx_report'),
    path('photo_approvals/', PhotoApprovalsDownloadView.as_view(), name='photo_apporvals'),
    path(
        'distribute_next_month/',
        DistributeNextMonthSchedules.as_view(),
        name='distribute_next_month',
    ),
    path(
        'next_month_plan_xlsx/',
        XlsxNextMonthDownloadView.as_view(),
        name='next_month_plan_xlsx',
    ),
    path('create/', ScheduleCreateView.as_view(), name='create_schedule'),
    path('schedules/<slug:start_date>/<slug:end_date>/', DateRangeScheduleView.as_view(), name='date_range'),
    path('calendar/', ScheduleCalendarView.as_view(), name='schedule_calendar'),
]

ppr_project/reports/views.py
import logging
from datetime import date, datetime, timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, RedirectView, TemplateView
from django.views.generic.edit import CreateView, FormView, UpdateView

from openpyxl.writer.excel import save_virtual_workbook
from simple_history.utils import bulk_update_with_history

from reports.forms import (CompleteScheduleForm, DateInputForm, DatePeriodForm,
                           ReportDownloadForm, ScheduleCreateForm,
                           ScheduleForm, ScheduleSearchForm,
                           UncompleteReasonForm)
from reports.models import MaintenanceCategory, Schedule
from reports.services import (XlsxReportGenerator,
                              distribute_next_month_works_by_dates,
                              download_photo_approvals, get_next_month_plans)

logger = logging.getLogger(__name__)


class IndexView(LoginRequiredMixin, RedirectView):
    """Redirect to today's schedules."""

    def get_redirect_url(self, *args, **kwargs):
        today = date.today()
        return reverse_lazy('reports:date_range', kwargs={'start_date': today, 'end_date': today})


class ScheduleListView(LoginRequiredMixin, ListView):
    model = Schedule
    template_name = 'reports/schedule_list.html'
    context_object_name = 'schedule_plan'

    SCHEDULE_ACTION_URLS = {
        'date_scheduled_changed': 'reports:confirm_date_changed',
        'schedule_completed': 'reports:confirm_schedule_completed',
        'schedule_cant_be_completed': 'reports:confirm_schedule_cant_complete'
    }

    def get(self, request, *args, **kwargs):
        request.session['return_url'] = self.request.get_full_path_info()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        selected_schedules = request.POST.getlist('selected_schedule')
        if not selected_schedules:
            messages.warning(self.request, 'Не выбрано ни одной работы!')
            return self.get(request, *args, **kwargs)
        selected_action = request.POST.get('selected_action')
        action_confirmation_url = self.SCHEDULE_ACTION_URLS.get(selected_action)
        if not action_confirmation_url:
            return self.get(request, *args, **kwargs)
        request.session['selected_schedules'] = selected_schedules
        return redirect(action_confirmation_url)

    def get_queryset(self):
        qs = (Schedule.objects.select_related('equipment_type__facility', 'report', 'maintenance_type')
                              .order_by('date_sheduled', 'equipment_type__facility'))
        category = self.request.GET.get('category', None)
        if category:
            maintenance_category = get_object_or_404(MaintenanceCategory, category_name=category)
            return qs.filter(equipment_type__maintenance_category=maintenance_category)
        return qs


class DateRangeScheduleView(ScheduleListView):
    def get_queryset(self, **kwargs):
        qs = super().get_queryset()
        date_format = '%Y-%m-%d'
        try:
            start_date_str = self.kwargs.get('start_date')
            self.start_date = datetime.strptime(start_date_str, date_format)
            end_date_str = self.kwargs.get('end_date')
            self.end_date = datetime.strptime(end_date_str, date_format)
            return qs.filter(date_sheduled__range=[self.start_date, self.end_date])
        except ValueError:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_format = '%d.%m.%Y'
        start_date = datetime.strftime(self.start_date, date_format)
        end_date = datetime.strftime(self.end_date, date_format)
        context['plan_period'] = f'План на период с {start_date} по {end_date}'
        return context


class SelectDateRangeForScheduleView(LoginRequiredMixin, FormView):
    form_class = DatePeriodForm
    template_name = 'reports/action_confirmation.html'

    def post(self, request, **kwargs):
        form = self.get_form(self.form_class)
        if form.is_valid():
            date_from = form.data.get('date_from')
            date_to = form.data.get('date_to')
            return redirect('reports:date_range', date_from, date_to)
        return self.get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_to_confirm'] = 'Выберите период'
        context['return_url'] = self.request.session.get('return_url')
        return context


class ScheduleDetailInfoView(LoginRequiredMixin, UpdateView):
    template_name = 'reports/schedule_detail.html'
    model = Schedule
    form_class = ScheduleForm
    context_object_name = 'schedule_entry'

    def get_success_url(self):
        return self.request.session.get('return_url')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_url'] = self.get_success_url()
        return context


class OverDueScheduleView(ScheduleListView):
    def get_queryset(self):
        qs = super().get_queryset()
        lte_date = date.today() - timedelta(days=1)
        return qs.filter(date_sheduled__lte=lte_date, uncompleted__isnull=True, date_completed__isnull=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plan_period'] = 'Просроченные работы'
        return context


class UncompletableScheduleView(ScheduleListView):
    """View uncompletable schedules for last three months."""

    def get_queryset(self):
        qs = super().get_queryset()
        date_gte = date.today() - timedelta(days=60)
        return qs.filter(
            uncompleted__reason__icontains='магистраль',
            date_completed__isnull=True,
            date_sheduled__gte=date_gte,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plan_period'] = 'Невыполнимые работы (последние три месяца)'
        return context


class NoPhotoScheduleView(ScheduleListView):
    """View completed schedules without photo approvals."""

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(date_completed__isnull=False, photo='', maintenance_type__m_type__icontains='Проверка')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plan_period'] = 'Завершенные проверки защит, к которым не загружены фото'
        return context


class ConfirmScheduleCompletedView(LoginRequiredMixin, FormView):
    form_class = CompleteScheduleForm
    template_name = 'reports/action_confirmation.html'

    def post(self, request, **kwargs):
        schedule_list = self.request.session.get('selected_schedules')
        return_url = self.request.session.get('return_url')
        form = self.get_form(self.form_class)
        if form.is_valid():
            qs = Schedule.objects.filter(pk__in=schedule_list)
            for entry in qs:
                entry._change_reason = 'Confirmed work completed'
                entry.date_completed = form.cleaned_data.get('date_completed')
                entry.employee1 = form.cleaned_data.get('employee1')
                entry.employee2 = form.cleaned_data.get('employee2')
                entry.employee3 = form.cleaned_data.get('employee3')
                entry.uncompleted = None
            bulk_update_with_history(
                qs, Schedule, ['date_completed', 'employee1', 'employee2', 'employee3'], batch_size=500)
            return redirect(return_url)
        return self.get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_url'] = self.request.session.get('return_url')
        context['action_to_confirm'] = 'Выберите дату и исполнителей'
        return context


class ConfirmScheduleDateChangedView(LoginRequiredMixin, FormView):
    form_class = DateInputForm
    template_name = 'reports/action_confirmation.html'

    def post(self, request, **kwargs):
        schedule_list = self.request.session.get('selected_schedules')
        return_url = self.request.session.get('return_url')
        form = self.get_form(self.form_class)
        if form.is_valid():
            qs = Schedule.objects.filter(pk__in=schedule_list)
            for entry in qs:
                entry._change_reason = 'Changed schedule date'
                entry.date_sheduled = form.cleaned_data.get('input_date')
            bulk_update_with_history(qs, Schedule, ['date_sheduled'], batch_size=500)
            return redirect(return_url)
        return self.get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_url'] = self.request.session.get('return_url')
        context['action_to_confirm'] = 'Выберите дату'
        return context


class ConfirmScheduleCannotBeComplete(LoginRequiredMixin, FormView):
    form_class = UncompleteReasonForm
    template_name = 'reports/action_confirmation.html'

    def post(self, request, **kwargs):
        schedule_list = self.request.session.get('selected_schedules')
        return_url = self.request.session.get('return_url')
        form = self.get_form(self.form_class)
        if form.is_valid():
            qs = Schedule.objects.filter(pk__in=schedule_list)
            for entry in qs:
                entry._change_reason = 'Marked as can not be completed'
                entry.uncompleted = form.cleaned_data.get('reason')
            bulk_update_with_history(qs, Schedule, ['uncompleted'], batch_size=500)

ppr_project/templates/reports/includes/modal_window.html
  <!-- Modal -->
  <div class="modal fade" id="modalWindow" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content" id="modalWindowContent">
        <div class="modal-header">
          <h5 class="modal-title">Загрузка...</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="spinner-border text-secondary" role="status">
            <span class="visually-hidden">Загрузка...</span>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        </div>
      </div>
    </div>
  </div>

ppr_project/templates/reports/includes/nav_tabs.html
{% load user_filters %}
{% get_maintenance_categories as category_list %}
<ul class="nav nav-tabs card-header-tabs">
  <li class="nav-item">
    <a class="nav-link {% if not request.GET.category %}active{% endif %}" href="?">Все объекты</a>
  </li>
  {% for cat in category_list %}
  <li class="nav-item">
    <a class="nav-link {% if request.GET.category == cat.category_name %}active{% endif %}" href="{{ request.get_path }}?category={{ cat.category_name }}">{{ cat.category_name }}</a>
  </li>
  {% endfor %}
</ul>

ppr_project/templates/reports/includes/schedule_table.html
<div class="container mt-2 mb-5">
  {% if not schedule_plan %}
    <div class="display-6 text-center">Работ не найдено!</div>
  {% else %}
    <form method="post" action="">
      {% csrf_token %}
      {# table header #}
      <div class="container">
        <div class="d-none d-lg-block">
          <div class="row border-bottom my-3 align-items-center">
            <div class="col-12 col-lg-2 text-muted">
              <div class="row">
                <div class="col-4">#</div>
                <div class="col-8">Тип ТО</div>
              </div>
            </div>
            <div class="col-12 col-lg-6 text-muted">Наименование оборудования</div>
            <div class="col-6 col-lg-1 text-muted">План</div>
            <div class="col-12 col-lg-3">
              <div class="row align-items-center">
                <div class="col-6 col-lg-4 text-muted"><small>Допуск</small></div>
                <div class="col-12 col-lg-4 text-muted"><small>Журнал ТО</small></div>
                <div class="col-12 col-lg-4 text-muted"><small>Факт</small></div>
              </div>
            </div>
          </div>
        </div>
        {# table body #}
        {% regroup schedule_plan by date_sheduled as plan_by_date %}
        {% for schedule_date in plan_by_date %}
        {# date scheduled #}
          <div class="row pt-5">
            <div class="col-12"><h5>{{ schedule_date.grouper }}</h5></div>
          </div>
          {% regroup schedule_date.list by equipment_type.facility as facility_list %}
          {% for facility in facility_list %}
              {# facility name with popover #}
              <div class="row text-center border-bottom">
                <div class="col-12 m-2">
                  <a tabindex="0"
                     class="h5 text-decoration-none link-dark"
                     data-bs-toggle="popover"
                     id="popover-{{ facility.grouper.pk }}"
                     >
                    {{ facility.grouper }}
                    {# popover body #}
                    <div hidden>
                      <div class="text-center" id="popover-{{ facility.grouper.pk }}-body">
                        <div class="btn-group-sm btn-group-vertical" role="group">
                          <button type="button" class="btn btn-outline-secondary" onclick="popoverSelectSchedules({{ facility.grouper.pk }});">Выбрать/снять все</button>
                          <button type="button" class="btn btn-outline-secondary" onclick="popoverMarkJournalsFilled({{ facility.grouper.pk }}, 'access_journal');">Журналы допуска</button>
                          <button type="button" class="btn btn-outline-secondary" onclick="popoverMarkJournalsFilled({{ facility.grouper.pk }}, 'result_journal');">Журналы ТО</button>
                        </div>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% for entry in facility.list %}
              {# table rows #}
                <div id="sheduleRow{{ entry.pk }}" class="row border-bottom my-auto py-1
                          {% now "Y-m-d" as today_date %}
                          {% if entry.uncompleted and not entry.date_completed %} bg-secondary bg-opacity-25 {% endif %}
                          {% if today_date > entry.date_sheduled|date:"Y-m-d" and not entry.date_completed  and not entry.uncompleted %} bg-danger bg-opacity-25{% endif %}
                          {% if entry.date_completed and entry.access_journal_filled and entry.result_journal_filled %} bg-success bg-opacity-25{% endif %}">
                  <div class="col-12 col-lg-2">
                    <div class="row">
                      <div class="col-2 col-lg-4">
                        <div class="form-check form-switch">
                          <input type="checkbox" name="selected_schedule" value="{{ entry.pk }}" class="form-check-input" title="Выбрать работу" data-popover="select-{{ facility.grouper.pk }}">
                        </div>
                      </div>
                      <div class="col-10 col-lg-8">{{ entry.maintenance_type }}</div>
                    </div>
                  </div>
                  <div class="col-12 col-lg-6">
                    <a class="text-decoration-none text-reset my_custom_text" href="{% url 'reports:schedule_detail' pk=entry.pk %}" title="Редактировать работу">
                      {{ entry.equipment_type }}
                    </a>
                  </div>
                  <div class="col-6 d-lg-none"><small>Дата по плану:</small></div>
                  <div class="col-6 col-lg-1">{{ entry.date_sheduled|date:"d.m.y" }}</div>
                  <div class="col-12 col-lg-3">
                    <div class="row">
                      <div class="col-6 d-lg-none"><small>Журнал допуска:</small></div>
                      <div class="col-6 col-lg-4">
                        <input type="checkbox"
                               class="form-check-input"
                               name="access_journal_filled"
                               value="{{ entry.pk }}"
                               onclick="markJournalCheckbox(this);"
                               {% if entry.access_journal_filled %} checked {% endif %}
                               data-popover="access_journal-{{ facility.grouper.pk }}">
                      </div>
                      <div class="col-6 d-lg-none"><small>Журнал ТО:</small></div>
                      <div class="col-6 col-lg-4">
                        <input type="checkbox"
                              class="form-check-input"
                              name="result_journal_filled"
                              value="{{ entry.pk }}"
                              onclick="markJournalCheckbox(this);"
                              {% if entry.result_journal_filled %} checked {% endif %}
                              data-popover="result_journal-{{ facility.grouper.pk }}">
                      </div>
                      <div class="col-6 d-lg-none"><small>Дата выполнения:</small></div>
                      <div class="col-6 col-lg-4">
                        {% if entry.date_completed %}{{ entry.date_completed|date:"d.m.y" }}{% else %}---{% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% endfor %}
          {% endfor %}
        </div>
        {# menu block #}
        <div class="card my-5 border-primary">
          <div class="card-header bg-primary text-white">Выберите действие для отмеченных работ:</div>
          <div class="card-body">
            <div class="input-group mb-3">
              <select name="selected_action" class="form-select">
                <option value="schedule_completed">Подтвердить, что работа выполнена</option>
                <option value="date_scheduled_changed">Изменить плановую дату выполнения работ</option>
                <option value="schedule_cant_be_completed">Отметить, что работа НЕ может быть выполнена</option>
              </select>
              <button type="submit" class="btn btn-primary">Применить</button>
            </div>
          </div>
        </div>
    </form>
  {% endif %}
</div>