ppr_project/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from api.views import EquipmentTypeViewSet, FacilityViewSet, ScheduleViewSet

app_name = 'api'

router = DefaultRouter()
router.register('schedules', ScheduleViewSet, basename='schedules')
router.register('facilities', FacilityViewSet, basename='facilities')
router.register('equipment_types', EquipmentTypeViewSet, basename='equipment_types')


urlpatterns = [
    path('', include(router.urls)),
]

ppr_project/ppr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('bugs/', include('bugtracker.urls', namespace='bugtracker')),
    path('ppradmin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ppr_project/reports/urls.py
from django.urls import path

from reports.views import (ConfirmScheduleCannotBeComplete,
                           ConfirmScheduleCompletedView,
                           ConfirmScheduleDateChangedView,
                           DateRangeScheduleView, DistributeNextMonthSchedules,
                           IndexView, NoPhotoScheduleView, OverDueScheduleView,
                           PhotoApprovalsDownloadView, ScheduleCalendarView,
                           ScheduleCreateView, ScheduleDetailInfoView,
                           SearchView, SelectDateRangeForScheduleView,
                           UncompletableScheduleView,
                           XlsxNextMonthDownloadView, XlsxReportDownloadView)

app_name = 'reports'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('overdue/<int:category_id>/', OverDueScheduleView.as_view(), name='overdue'),
    path('overdue/', OverDueScheduleView.as_view(), name='overdue'),
    path('uncompletable/', UncompletableScheduleView.as_view(), name='uncompletable'),
    path('no_photo_apporval/', NoPhotoScheduleView.as_view(), name='no_photo_apporval'),
    path('search/', SearchView.as_view(), name='search'),
    path('select_date_range/', SelectDateRangeForScheduleView.as_view(), name='select_date_range'),
    path('schedule/<int:pk>/', ScheduleDetailInfoView.as_view(), name='schedule_detail'),
    path('schedule/confirm_completed/', ConfirmScheduleCompletedView.as_view(), name='confirm_schedule_completed'),
    path('schedule/confirm_date_changed/', ConfirmScheduleDateChangedView.as_view(), name='confirm_date_changed'),
    path(
        'schedule/confirm_cant_complete/',
        ConfirmScheduleCannotBeComplete.as_view(),
        name='confirm_schedule_cant_complete'
    ),
    path('xlsx_report/', XlsxReportDownloadView.as_view(), name='xlsx_report'),
    path('photo_approvals/', PhotoApprovalsDownloadView.as_view(), name='photo_apporvals'),
    path(
        'distribute_next_month/',
        DistributeNextMonthSchedules.as_view(),
        name='distribute_next_month',
    ),
    path(
        'next_month_plan_xlsx/',
        XlsxNextMonthDownloadView.as_view(),
        name='next_month_plan_xlsx',
    ),
    path('create/', ScheduleCreateView.as_view(), name='create_schedule'),
    path('schedules/<slug:start_date>/<slug:end_date>/', DateRangeScheduleView.as_view(), name='date_range'),
    path('calendar/', ScheduleCalendarView.as_view(), name='schedule_calendar'),
]

ppr_project/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/done/', views.SignUpDone.as_view(), name='signup_done'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/', views.ResetPassword.as_view(), name='password_reset'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

ppr_project/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings

from users.tasks import send_email_task

User = get_user_model()


class UserSignUpForm(UserCreationForm):

    email = forms.EmailField(
        required=True,
        label='Email адрес'
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

    def save(self):
        user = super().save(commit=False)
        user.is_active = False
        user.save()
        subject = 'New user signed up!'
        message = ('New user signed up on KS45 PPR PROJECT SYSTEM: '
                   f'{user.get_full_name()}!')
        admin_mailboxes = [a[1] for a in settings.ADMINS]
        send_email_task.delay(subject, message, admin_mailboxes)
        return user

ppr_project/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from users.forms import UserSignUpForm


class SignUp(CreateView):
    form_class = UserSignUpForm
    success_url = reverse_lazy('users:signup_done')
    template_name = 'users/signup.html'


class SignUpDone(TemplateView):
    template_name = 'users/signup_done.html'


class ResetPassword(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'

ppr_project/templates/users/base_without_navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'includes/styles_and_fonts.html' %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Система управления техническим обслуживанием{% endblock title %}</title>
  </head>
  <body>
      {% block content %}Контент{% endblock content %}
    {% include 'includes/scripts.html' %}
  </body>
</html>

ppr_project/templates/users/logged_out.html
{% extends 'users/includes/card_with_notification_no_navbar.html' %}
{% block title %}Выход из системы{% endblock title %}
{% block header_text %}Выход из системы{% endblock header_text %}
{% block card_text %}Вы вышли из системы{% endblock card_text %}
{% block additional_link %}
<div class="text-center">
  <p><a class="text-decoration-none" href="{% url 'users:login'%}" role="button">Войти в систему</a></p>
</div>
{% endblock additional_link %}

ppr_project/templates/users/login.html
{% extends 'users/base_without_navbar.html' %}
{% block title %}Вход в систему{% endblock title %}
{% block content %}
  {% comment %} custom links here, so not using includes/card_with_form (don't want to overload it just for this temlate) {% endcomment %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <div class="card">
        <div class="card-header h4"><strong>Войти в систему</strong></div>
          <div class="card-body">
            {% load user_filters %}
            {# ERRORS #}
            {% if form.errors %}
              {# field errors #}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {# non-field errors #}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}    
            {# FORM #}
            <form method="POST" action="">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  {# label #}
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {# field #}
                  {{ field|addclass:'form-control' }} 
                  {# helptext #}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
                {% endfor %}
              {# BUTTONS #}
              <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Войти</button>
                <a class="text-decoration-none m-2" href="{% url 'users:signup'%}" role="button">Регистрация</a>
              </div>
            </form>
          </div>
      </div>
      <div class="text-center">
        <p><a class="text-decoration-none" href="{% url 'users:password_reset'%}" role="button">Забыл пароль?</a></p>
      </div>      
    </div>
  </div>
{% endblock content %}

ppr_project/templates/users/password_change_done.html
{% extends 'users/includes/card_with_notification_no_navbar.html' %}
{% block title %}Изменение пароля{% endblock title %}
{% block header_text %}Изменение пароля{% endblock header_text %}
{% block card_text %}Пароль успешно изменен!{% endblock card_text %}
{% block additional_link %}
<div class="text-center">
  <p><a class="text-decoration-none" href="{% url 'reports:index'%}" role="button">На главную</a></p>
</div>
{% endblock additional_link %}

ppr_project/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock title %}
{% block content %}
  {% with card_header="Изменение пароля" submit_button="Изменить" %}
  {% url 'reports:index' as  cancel_url %}
    {% include 'users/includes/card_with_form.html' %}
  {% endwith %}
{% endblock content %}

ppr_project/templates/users/password_reset_complete.html
{% extends 'users/includes/card_with_notification_no_navbar.html' %}
{% block title %}Пароль изменен{% endblock title %}
{% block header_text %}Пароль изменен{% endblock header_text %}
{% block card_text %}
<p class="display">Пароль успешно изменен! Вы можете использовать новый пароль для входа в систему.</p>
{% endblock card_text %}
{% block additional_link %}
<div class="text-center">
  <p><a class="text-decoration-none" href="{% url 'users:login'%}" role="button">Войти в систему</a></p>
</div>
{% endblock additional_link %}

ppr_project/templates/users/password_reset_confirm.html
{% extends 'users/base_without_navbar.html' %}
{% block title %}Изменение пароля{% endblock title %}
{% block content %}
  {% if validlink %}
    {% with card_header="Изменение пароля" submit_button="Изменить" %}
    {% url 'reports:index' as  cancel_url %}
      {% include 'users/includes/card_with_form.html' %}
    {% endwith %}
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <div class="card">
        <div class="card-header h4"><strong>Изменение пароля</strong></div>
          <div class="card-body">
            <div class="col-md-12 text-center">
              <p class="display">Ссылка, которую вы используете, содержит ошибку либо устарела!</p>
            </div>
          </div>
      </div>
    </div>
  </div>
  {% endif %}
{% endblock content %}

ppr_project/templates/users/password_reset_done.html
{% extends 'users/includes/card_with_notification_no_navbar.html' %}
{% block title %}Сброс пароля{% endblock title %}
{% block header_text %}Сброс пароля{% endblock header_text %}
{% block card_text %}
  <p class="display">Инструкции для сброса пароля отправлены на указанную почту (если аккаунт с таким адресом почты существует)</p>
{% endblock card_text %}

ppr_project/templates/users/password_reset_email.html
Вы получили это письмо, потому что вы (или кто-то другой) запросили восстановление пароля от учётной записи , которая связана с этим адресом электронной почты.

Для сброса пароля, пожалуйста, перейдите по ссылке и введите новый пароль:

https://www.ks-45.ru{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Ваше имя пользователя (на случай, если вы его забыли): {{ user }}

Спасибо, что используете наш сайт!

Администрация

ppr_project/templates/users/password_reset_form.html
{% extends 'users/base_without_navbar.html' %}
{% block title %}Сброс пароля{% endblock title %}
{% block content %}
  {% with card_header="Сброс пароля" submit_button="Сбросить пароль" %}
  {% url 'users:login' as  cancel_url %}
    {% include 'users/includes/card_with_form.html' %}
  {% endwith %}
{% endblock content %}

ppr_project/templates/users/signup.html
{% extends 'users/base_without_navbar.html' %}
{% block title %}Регистрация{% endblock title %}
{% block content %}
  {% with card_header="Регистрация в системе" submit_button="Зарегистрироваться" %}
  {% url 'users:login' as  cancel_url %}
    {% include 'users/includes/card_with_form.html' %}
  {% endwith %}
{% endblock content %}

ppr_project/templates/users/signup_done.html
{% extends 'users/includes/card_with_notification_no_navbar.html' %}
{% block title %}Регистрация в системе{% endblock title %}
{% block header_text %}Регистрация в системе{% endblock header_text %}
{% block card_text %}
<p class="display">
Вы успешно зарегистрировались!
Пожалуйста, ожидайте одобрение вашего аккаунта администратором.
Когда Ваш аккаунт будет одобрен, вы сможете использовать его для входа в систему. Вы получите уведомление по электронной почте
</p>
<p class="display"><small>Для ускорения процесса, Вы можете связаться с администратором (С.И.А.) любым удобным способом.</small></p>
{% endblock card_text %}
{% block additional_link %}
<div class="text-center">
  <p><a class="text-decoration-none" href="{% url 'users:login'%}" role="button">Перейти на страницу входа</a></p>
</div>
{% endblock additional_link %}