ppr_project/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from api.views import EquipmentTypeViewSet, FacilityViewSet, ScheduleViewSet

app_name = 'api'

router = DefaultRouter()
router.register('schedules', ScheduleViewSet, basename='schedules')
router.register('facilities', FacilityViewSet, basename='facilities')
router.register('equipment_types', EquipmentTypeViewSet, basename='equipment_types')


urlpatterns = [
    path('', include(router.urls)),
]

ppr_project/bugtracker/urls.py
from django.urls import path
from bugtracker import views


app_name = 'bugtracker'

urlpatterns = [
    path('', views.BugListView.as_view(), name='index'),
    path('create/', views.BugCreateView.as_view(), name='create'),
    path('<int:pk>/', views.BugDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', views.AddCommentView.as_view(), name='comment'),
    path('<int:pk>/close/', views.CloseBug.as_view(), name='close'),
]

ppr_project/ppr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('bugs/', include('bugtracker.urls', namespace='bugtracker')),
    path('ppradmin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ppr_project/bugtracker/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import signals
from django.dispatch import receiver

from users.tasks import send_email_task

User = get_user_model()

BUG_TYPE_CHOICES = [
    ('BG', 'Замечание'),
    ('FT', 'Предложение')
]


class Bug(models.Model):
    type = models.CharField(
        max_length=150,
        choices=BUG_TYPE_CHOICES,
        verbose_name='Тип',
        help_text='Выберите тип'
    )
    bug_description = models.TextField(
        verbose_name='Описание',
        help_text='Введите описание'
    )
    screenshot = models.ImageField(
        upload_to='bugtracker/%Y/%m/%d',
        blank=True,
        verbose_name='Скриншот или фото'
    )
    pub_date = models.DateField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    close_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Дата устранения/внедрения'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name='Автор',
        null=True,
        blank=True
    )

    class Meta:

        ordering = ['-pub_date']
        verbose_name = 'Замечание/предложение'
        verbose_name_plural = 'Замечания/предложения'

    def __str__(self):
        return f'{self.get_type_display()}: {self.bug_description[:20]}...'


class Comment(models.Model):

    bug = models.ForeignKey(
        Bug,
        on_delete=models.CASCADE,
        verbose_name='Предложение/замечание',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        help_text='Введите текст комментария',
        verbose_name='Текст комментария'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время комментария'
    )

    class Meta:

        ordering = ['-created_at']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.author}: {self.text[:20]}...'


@receiver(signals.post_save, sender=Bug)
def notify_admins_bug_entry_created(sender, instance, created, **kwargs):
    if created:
        subject = 'New bug/feature submitted!'
        message = ('Hello! We have got a new bug entry at ks-45.ru: \n'
                   f'Pub date: {instance.pub_date}\n'
                   f'Type: {instance.get_type_display()}\n'
                   f'Author: {instance.author.username}\n'
                   f'Description: {instance.bug_description}\n'
                   f'Check it out here: https://ks-45.ru/bugs/')
        admin_mailboxes = [a[1] for a in settings.ADMINS]
        send_email_task.delay(subject, message, admin_mailboxes)


@receiver(signals.post_save, sender=Comment)
def notify_user_bug_entry_commented(sender, instance, created, **kwargs):
    if created and instance.bug.author != instance.author:
        bug_author = instance.bug.author
        subject = 'Новый комментарий к твоему замечанию в ППР КС-45'
        message = (
            f'Привет {bug_author.username}!\n'
            f'Твое {instance.bug.get_type_display()} прокомментировали.\n'
            f'Автор комментария: {instance.author.username}\n'
            f'Текст комментария: {instance.text}\n'
            f'Подробнее тут: https://ks-45.ru/bugs/{instance.bug.pk}/')
        send_email_task.delay(subject, message, [bug_author.email])


@receiver(signals.post_save, sender=Bug)
def notify_user_bug_closed(sender, instance, created, **kwargs):
    if instance.close_date is not None:
        subject = f'{instance.get_type_display()} выполнено в ППР КС-45'
        message = (f'Привет {instance.author.username}!\n'
                   'Отличные новости!\n'
                   f'{instance.get_type_display()}, которое ты оставлял в '
                   'системе управления ППР КС-45, отмечено как выполненное.\n'
                   f'Подробнее тут: https://ks-45.ru/bugs/{instance.pk}/')
        send_email_task.delay(subject, message, [instance.author.email])

ppr_project/bugtracker/forms.py
from django import forms
from bugtracker.models import Bug, Comment


class BugForm(forms.ModelForm):

    class Meta:
        model = Bug
        fields = ('type', 'bug_description', 'screenshot')


class CommentForm(forms.ModelForm):

    class Meta:

        model = Comment
        fields = ('text',)

ppr_project/bugtracker/views.py
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from bugtracker.forms import BugForm, CommentForm
from bugtracker.models import Bug, Comment


class BugListView(LoginRequiredMixin, ListView):
    model = Bug
    context_object_name = 'bugs'
    template_name = 'bugtracker/index.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BugForm()
        return context


class BugCreateView(LoginRequiredMixin, CreateView):
    form_class = BugForm
    model = Bug
    success_url = reverse_lazy('bugtracker:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.pub_date = date.today()
        return super().form_valid(form)


class BugDetailView(LoginRequiredMixin, DetailView):
    template_name = 'bugtracker/bug_detail.html'
    model = Bug
    context_object_name = 'bug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bug = self.get_object()
        context['comment_form'] = CommentForm()
        context['bug_comments'] = bug.comments.all()
        return context


class AddCommentView(LoginRequiredMixin, CreateView):

    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.bug = get_object_or_404(Bug, pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('bugtracker:detail', kwargs={'pk': self.kwargs['pk']})


class CloseBug(UserPassesTestMixin, View):
    """
    Close bug. Closing bug means that close_date field of Bug model is
    set to now(). Allowed only to staff users.
    """

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request, **kwargs):
        bug = get_object_or_404(Bug, pk=self.kwargs['pk'])
        bug.close_date = date.today()
        bug.save()
        return redirect('bugtracker:detail', kwargs['pk'])

ppr_project/templates/bugtracker/bug_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<div class="row my-3">
<aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
          #<span>{{ bug.pk }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
          Дата публикации:<span>{{ bug.pub_date|date:"d E Y" }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Тип:<span>{{ bug.get_type_display }}</span>
      </li>    
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Автор: <span>{{ bug.author.username }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Дата выполнения: <span>{% if not bug.close_date %} --- {% else %}{{ bug.close_date|date:"d E Y"  }}{% endif %}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a class="text-decoration-none" href="{% url 'bugtracker:index' %}">Вернуться к списку</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9 my-2">
    {% thumbnail bug.screenshot "960x339" crop="center" upscale=True as im %}
    <a href="{{ bug.screenshot.url }}" target="_blank"><img class="card-img my-2" src="{{ im.url }}"></a>
    {% endthumbnail %}
    <p class="mb-5">
      {{ bug.bug_description }}
    </p>
    <hr>
    <section>
      <p class="h5 mb-3">Комментарии:</p>
      {% include 'bugtracker/comments.html' %}
    </section>
  </article>
</div> 
{% endblock content %}

ppr_project/templates/bugtracker/bug_form.html
<div class="row my-4">
  <div class="col-lg-6">
    <div class="card">
        <div class="card-body">
            {% load user_filters %}
            {# ERRORS #}
            {% if form.errors %}
            {# field errors #}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {# non-field errors #}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }} 
                </div>
              {% endfor %}
            {% endif %}
            
            {# FORM #}
            <form method="post" action="{% url 'bugtracker:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  {# label #}
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                  {# field #}
                  {{ field|addclass:'form-control' }} 
                  {# helptext #}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
          {# BUTTONS #}
          <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Добавить</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

ppr_project/templates/bugtracker/comments.html
{% load user_filters %}
{% for comment in bug_comments %}
<div class="media mb-4">
  <div class="media-body">
    <p class="mb-1">
      <strong>{{ comment.author.username }}</strong> <span class="small text-muted">- {{ comment.created_at }}</span>
    </p>
  </div>
  <div>
    {{ comment.text }}
  </div>
</div>
{% endfor %}

<div class="card my-4">
<h6 class="card-header">Добавить комментарий</h6>
    <div class="card-body">
    <form method="POST" action="{% url 'bugtracker:comment' bug.pk %}">
      {% csrf_token %}
        <div class="form-group mb-2">
          {{ comment_form.text|addclass:"form-control" }}
        </div>
      <button type="submit" class="btn btn-primary btn-sm">Отправить</button>
      {% if user.is_staff %}
        <a class="btn btn-danger btn-sm" href="{% url 'bugtracker:close' bug.pk %}" role="button">Закрыть баг</a>
      {% endif %}
    </form>
    </div>     
</div>

ppr_project/templates/bugtracker/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row d-flex justify-content-center my-2">
  <div class="col">
    <div class="card shadow-0 border" style="background-color: #f0f2f5;">
      <div class="card-body p-4">
        <div class="mb-4">
          <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseCreationForm" role="button" aria-expanded="false" aria-controls="collapseExample">+ Добавить замечание или предложение</a>
        </div>
        <div class="collapse" id="collapseCreationForm">
          {% include 'bugtracker/bug_form.html' %}
        </div>
        {% for bug in bugs %}
          <div class="card mb-2">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                  <p><strong>{{ bug.author }} </strong><span class="small text-muted">- {{ bug.pub_date }}</span></p>
                </div>
                <div class="d-flex flex-row align-items-center">
                  <a class="small text-muted mb-0 text-decoration-none" href="{% url 'bugtracker:detail' bug.pk %}" title="Комментарии"><i class="fas fa-comment"></i>  {{ bug.comments.count }}</a>
                </div>
              </div>
              <a class="mb-0 text-decoration-none text-reset" href="{% url 'bugtracker:detail' bug.pk %}">{{ bug.bug_description }}</a>
              <p>
                {% if bug.screenshot %}
                  <a class="text-decoration-none" href="{{ bug.screenshot.url }}">Посмотреть фото</a>
                {% endif %}
              </p>
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                  <p class="small text-muted mb-0">{{ bug.get_type_display }}</p>
                </div>
                <div class="d-flex flex-row align-items-center">
                  {% if bug.close_date %}<p class="small text-muted mb-0">Выполнено {{ bug.close_date }}</p>
                  {% else %} <div class="badge bg-primary text-wrap" style="width: 6rem;">В работе</div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% include 'bugtracker/pagination.html' %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

ppr_project/templates/bugtracker/pagination.html
{# Pagination #}
{% if is_paginated %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1"><span>&laquo;</span> </a></li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><span>&raquo;</span></a></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}