ppr_project/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from api.views import EquipmentTypeViewSet, FacilityViewSet, ScheduleViewSet

app_name = 'api'

router = DefaultRouter()
router.register('schedules', ScheduleViewSet, basename='schedules')
router.register('facilities', FacilityViewSet, basename='facilities')
router.register('equipment_types', EquipmentTypeViewSet, basename='equipment_types')


urlpatterns = [
    path('', include(router.urls)),
]

ppr_project/ppr_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('bugs/', include('bugtracker.urls', namespace='bugtracker')),
    path('ppradmin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ppr_project/reports/urls.py
from django.urls import path

from reports.views import (ConfirmScheduleCannotBeComplete,
                           ConfirmScheduleCompletedView,
                           ConfirmScheduleDateChangedView,
                           DateRangeScheduleView, DistributeNextMonthSchedules,
                           IndexView, NoPhotoScheduleView, OverDueScheduleView,
                           PhotoApprovalsDownloadView, ScheduleCalendarView,
                           ScheduleCreateView, ScheduleDetailInfoView,
                           SearchView, SelectDateRangeForScheduleView,
                           UncompletableScheduleView,
                           XlsxNextMonthDownloadView, XlsxReportDownloadView)

app_name = 'reports'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('overdue/<int:category_id>/', OverDueScheduleView.as_view(), name='overdue'),
    path('overdue/', OverDueScheduleView.as_view(), name='overdue'),
    path('uncompletable/', UncompletableScheduleView.as_view(), name='uncompletable'),
    path('no_photo_apporval/', NoPhotoScheduleView.as_view(), name='no_photo_apporval'),
    path('search/', SearchView.as_view(), name='search'),
    path('select_date_range/', SelectDateRangeForScheduleView.as_view(), name='select_date_range'),
    path('schedule/<int:pk>/', ScheduleDetailInfoView.as_view(), name='schedule_detail'),
    path('schedule/confirm_completed/', ConfirmScheduleCompletedView.as_view(), name='confirm_schedule_completed'),
    path('schedule/confirm_date_changed/', ConfirmScheduleDateChangedView.as_view(), name='confirm_date_changed'),
    path(
        'schedule/confirm_cant_complete/',
        ConfirmScheduleCannotBeComplete.as_view(),
        name='confirm_schedule_cant_complete'
    ),
    path('xlsx_report/', XlsxReportDownloadView.as_view(), name='xlsx_report'),
    path('photo_approvals/', PhotoApprovalsDownloadView.as_view(), name='photo_apporvals'),
    path(
        'distribute_next_month/',
        DistributeNextMonthSchedules.as_view(),
        name='distribute_next_month',
    ),
    path(
        'next_month_plan_xlsx/',
        XlsxNextMonthDownloadView.as_view(),
        name='next_month_plan_xlsx',
    ),
    path('create/', ScheduleCreateView.as_view(), name='create_schedule'),
    path('schedules/<slug:start_date>/<slug:end_date>/', DateRangeScheduleView.as_view(), name='date_range'),
    path('calendar/', ScheduleCalendarView.as_view(), name='schedule_calendar'),
]

ppr_project/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/done/', views.SignUpDone.as_view(), name='signup_done'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/', views.ResetPassword.as_view(), name='password_reset'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_change/',
         PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

ppr_project/templates/includes/footer.html
<footer class="bg-light text-center text-lg-start mt-auto">
  <div class="text-center p-2 mt-3">
    <p class="text-muted">© 2023 Copyright: Ivan Skvortsov <br/>
      Версия 1.8.0
    </p>
    <p class="text-muted mt-1"></p>
  </div>
</footer>

ppr_project/templates/includes/navbar.html
{% load static %}
{% load user_filters %}
{% count_overdue_schedules as count_overdue %}
{% count_uncompletable_schedules as count_uncomletable %}
{% count_schedules_without_photo_approvals as count_no_photo %}
{% current_day_date_range as current_day_dates %}
{% current_week_date_range as current_week_dates %}
{% current_month_date_range as current_month_dates %}
{% next_month_date_range as next_month_dates %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-xxl">
    <a class="navbar-brand" href="{% url 'reports:index' %}">
      <img src="{% static 'img/navbar_logo.png' %}" alt="" width="50" height="50">
      <span class="text-muted">Выполнение ППР КС-45</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            <i class="fas fa-download"></i> Загрузки
          </a>
          <ul class="dropdown-menu">
            <li>
              <button
                class="dropdown-item btn btn-link"
                {% if count_overdue or count_no_photo%}
                  disabled
                {% endif %}
                style="cursor:pointer"
                onclick="showModalForm({% url 'reports:xlsx_report' %});">
                  <i class="fas fa-file"></i> Протокол выполнения
              </buitton>
            </li>
            <li><a class="dropdown-item" href="{% url 'reports:next_month_plan_xlsx' %}"><i class="fas fa-table"></i> План на следующий месяц</a></li>
            <li><a class="dropdown-item" style="cursor:pointer" href="{% url 'reports:photo_apporvals' %}"><i class="fas fa-images"></i> Подтверждающие фото</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            <i class="fas fa-wrench"></i> Посмотреть план
            {% if count_overdue or count_no_photo%}
              <span class="badge badge-pill bg-danger">{{ count_overdue|add:count_no_photo }}</span>
            {% endif %}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'reports:date_range' current_day_dates.0 current_day_dates.1 %}">Сегодня</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:date_range' current_week_dates.0 current_week_dates.1 %}">Эта неделя</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:date_range' current_month_dates.0 current_month_dates.1 %}">Этот месяц</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:date_range' next_month_dates.0 next_month_dates.1 %}">Следующий месяц</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:select_date_range' %}">Выбрать период</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item" href="{% url 'reports:overdue' %}">
                Просроченные
                <span class="badge badge-pill {% if count_overdue %}bg-danger{% else %}bg-secondary{% endif %}">{{ count_overdue }}</span>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'reports:uncompletable' %}">
                Невыполнимые
                <span class="badge badge-pill bg-secondary">{{ count_uncomletable }}</span>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'reports:no_photo_apporval' %}">
                Не загружено фото
                <span class="badge badge-pill {% if count_no_photo %}bg-danger{% else %}bg-secondary{% endif %}">{{ count_no_photo }}</span>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            <i class="fas fa-edit"></i> Редактировать план
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'reports:create_schedule' %}"><i class="far fa-calendar-plus"></i> Добавить работу</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:distribute_next_month' %}"><i class="fas fa-random"></i> Распределить следующий месяц</a></li>
            <li><a class="dropdown-item" href="{% url 'reports:schedule_calendar' %}"><i class="far fa-calendar-alt"></i> Календарь<span class="badge bg-info">beta</span></a></li>
          </ul>
        </li>





        <li class="nav-item">
          <a class="nav-link" href="{% url 'reports:search' %}"><i class="fas fa-search"></i> Поиск работ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bugtracker:index' %}"><i class="fas fa-bug"></i> Замечания к системе</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            <i class="fas fa-user"></i> {{ user.get_username }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'users:password_change' %}"><i class="fas fa-key"></i> Изменить пароль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Выйти</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
{% include 'reports/includes/modal_window.html' %}
</nav>

ppr_project/templates/includes/scripts.html
{% load static %}
{# bootstrap #}
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>

{# static #}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/popovers.js' %}" defer></script>

ppr_project/templates/includes/styles_and_fonts.html
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>

<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  \
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>

<link
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
  rel="stylesheet"
/>